Development 3.0.0
codescalersinternships/test-tracker pull request #39
Opened 2024-07-23 13:30 UTC by moriyad12

### Description
Add project skeleton vue3

### Changes
adding components folder
adding utilities folder
adding api folder 
adding types folder

### Related Issues
https://github.com/codescalersinternships/test-tracker/issues/18

2024-07-24 10:40 UTC, maayarosama requested changes

2024-07-24 10:40 UTC, maayarosama commented on client/src/api/axios.ts
need to add another one instance with headers

2024-07-24 10:40 UTC, maayarosama commented on client/src/components/test.ts
components directory shouldn't contains ts files, only vue files

2024-07-28 10:15 UTC, moriyad12 commented on client/src/api/axios.ts
done

2024-07-28 10:15 UTC, moriyad12 commented on client/src/components/test.ts
done

2024-07-28 10:28 UTC, maayarosama requested changes

2024-07-28 10:28 UTC, maayarosama commented on client/src/api/axios.ts
> +    'Authorization': 'Bearer ',
```suggestion
      Authorization: "Bearer " + localStorage.getItem("token"),

```

2024-07-28 10:28 UTC, maayarosama commented on client/src/api/axios.ts
> +  baseURL: 'https://your-api-base-url.com',
```suggestion
  baseURL: import.meta.env.vite_app_endpoint, 

```

2024-07-28 10:28 UTC, maayarosama commented on client/src/api/axios.ts
> +  headers: {
no need for this

2024-07-28 10:28 UTC, maayarosama commented on client/src/api/axios.ts
> +  baseURL: 'https://your-api-base-url.com',
same as above

2024-07-28 10:28 UTC, maayarosama commented on client/src/api/axios.ts
> +const axiosInstanceWithoutAuth: AxiosInstance = axios.create({
```suggestion
const BaseClient: AxiosInstance = axios.create({

```

2024-07-28 10:28 UTC, maayarosama commented on client/src/api/axios.ts
> +const axiosInstanceWithAuth: AxiosInstance = axios.create({
```suggestion
const AuthClient: AxiosInstance = axios.create({

```

2024-07-28 11:41 UTC, maayarosama approved these changes

2024-07-28 11:41 UTC, merged