Update client readme file
codescalersinternships/test-tracker pull request #45
Opened 2024-08-08 08:27 UTC by abdahmed22

### Description

Update client readme file to include introduction, features, setup and tests. 
### Changes

-  Introduction describing the project 
- Test tracker features 
- How to Setup on a local machine
- How to run tests

### Related Issues

- https://github.com/codescalersinternships/test-tracker/issues/36

2024-08-08 09:52 UTC, maayarosama requested changes

2024-08-08 09:52 UTC, maayarosama commented on client/README.md
> +TestTracker allows the entire team to manage their test plans, requirements, test cases and test runs in a simple and efficient way. All essential tools to manage your test cases all in one place.
```suggestion
TestTracker allows the QA team to manage their test plans, requirements, test cases and test runs in a simple and efficient way. All essential tools to manage your test cases all in one place. 
```

2024-08-08 09:52 UTC, maayarosama commented on client/README.md
> +## Features
Th features part isn't needed, you can remove it

2024-08-08 09:52 UTC, maayarosama commented on client/README.md
> +   user@user-VirtualBox:~$ make install
```suggestion
  ```make install```
```
apply to all other commands

2024-08-08 09:52 UTC, maayarosama commented on client/README.md
add prerequisites section and move the readme file to the root directory

2024-08-13 08:19 UTC, zaelgohary requested changes

2024-08-13 08:19 UTC, zaelgohary commented on README.md
> +## <a name="table-contents">Table of Contents</a>
```suggestion
## Table of Contents
```

2024-08-13 08:19 UTC, zaelgohary commented on README.md
> +## <a name="table-contents">Table of Contents</a>
This applies on all headers.

2024-08-13 08:19 UTC, zaelgohary commented on README.md
> +5.  [Tests](#tests)
```suggestion
1. [Introduction](#introduction)
2. [Prerequisites](#prerequisites)
3. [Setup on Your Local Machine](#setup-on-your-local-machine)
4. [Setup Using Docker](#setup-using-docker)
5. [Tests](#tests)
```

2024-08-13 08:19 UTC, zaelgohary commented on README.md
> +* Docker - [Download & Install Docker](https://docs.docker.com/engine/install/). Skip this step if you plan to use your local machine to run Test Tracker.
```suggestion
- **Git** - [Download & Install Git](https://git-scm.com/downloads). OSX and Linux machines typically have this already installed.
- **Node.js** - [Download & Install Node.js](https://nodejs.org/en/download/) and the pnpm package manager. If you encounter any problems, you can also use this [GitHub Gist](https://gist.github.com/isaacs/579814) to install Node.js.
- **Python3** - [Download & Install Python3](https://www.python.org/downloads/).
- **Poetry** - [Download & Install Poetry](https://python-poetry.org/docs/).
- **Docker** - [Download & Install Docker](https://docs.docker.com/engine/install/). Skip this step if you plan to use your local machine to run Test Tracker.

```

2024-08-13 08:19 UTC, zaelgohary commented on README.md
> +## <a name="local-setup">Setup on your local machine</a>
```suggestion
## Setup on Your Local Machine
```

2024-08-13 08:19 UTC, zaelgohary commented on README.md
> +2. Create .env file using the following template:
```suggestion
1. Clone the repository to a directory of your choice.
2. Create a `.env` file using the following template:
```

2024-08-13 08:19 UTC, zaelgohary commented on README.md
> +        DJANGO_SUPERUSER_PASSWORD=
```suggestion
    ```env
    # === General ===        
    DJANGO_SECRET_KEY=
    SERVER_DOMAIN_NAME=
    SERVER_DOMAIN_NAME_API=
    CLIENT_DOMAIN_NAME=
    ENV=production
    DJANGO_DEBUG=OFF
    
    # === Email ===
    EMAIL=
    EMAIL_PASSWORD=
    EMAIL_HOST=
    
    # === Database ===
    DATABASE_NAME=
    DATABASE_USER=
    DATABASE_PASSWORD=
    DATABASE_HOST=
    DATABASE_PORT=
    
    DJANGO_SUPERUSER_EMAIL=
    DJANGO_SUPERUSER_PASSWORD=
    ```
```

2024-08-13 08:19 UTC, zaelgohary commented on README.md
> +    make install
```suggestion
    ```console
    make install
    ```
```

2024-08-13 08:19 UTC, zaelgohary commented on README.md
> +    make runclient
Same here in all console commands.

2024-08-13 08:33 UTC, zaelgohary commented on client/README.md
> +  Create a defaullt test plan
```suggestion
  Create a default test plan
```

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  Logout
Convert to an unordered list.

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  Search for a member
Same here.

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  Search for a project
and here.

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  Add new test plan
```suggestion
  Add a new test plan
```

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  Add new test requirments
```suggestion
  Add new test requirements
```

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  Add new test suite
```suggestion
  Add a new test suite
```

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  Add new test run
```suggestion
  Add a new test run
```

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  View Statistics
```suggestion
  View statistics
```

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  Search for a test plan
convert to an unordered list.

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  Create a defaullt test plan
```suggestion
  Create a default test plan
```

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  Search for a requirment
Same here.

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  <p>&nbsp;</p>
```suggestion
```

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  <p>&nbsp;</p>
```suggestion

```

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  <p>&nbsp;</p>
```suggestion
```

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  <p>&nbsp;</p>
```suggestion
```

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  Search for a test case
same here.

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  <p>&nbsp;</p>
```suggestion
```

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  <p>&nbsp;</p>
```suggestion
```

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  Involve a team member
same.

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  <p>&nbsp;</p>
```suggestion
```

2024-08-13 08:48 UTC, zaelgohary commented on client/README.md
> +  Add existing test case
```suggestion
- Add a test case section
- Add a new test case
- Add an existing test case
```

2024-08-13 09:41 UTC, abdahmed22 commented on client/README.md
> +  Create a defaullt test plan
I removed the features section

2024-08-13 10:14 UTC, zaelgohary approved these changes

2024-08-13 10:47 UTC, merged